version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx
    ports:
     - "443:443"
    depends_on:
      - wordpress
    volumes:
     - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    image: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
  
  static-web:
    container_name: website
    build: ./requirements/bonus/website/.
    restart: always
    ports:
      - 80:80
    networks:
      - inception

volumes:
        wordpress:
                driver: local
                driver_opts:
                        device: /home/${USER}/data/wordpress
                        o: bind
                        type: none
        mariadb:
                driver: local
                driver_opts:
                        device: /home/${USER}/data/mariadb
                        o: bind
                        type: none

networks:
  inception:
    driver: bridge
